Source/DebateApp.Mvc/Models/ErrorViewModel.cs
using System;

namespace DebateApp.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Source/DebateApp.Mvc/Models/RoundRegistrationDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DebateApp.Mvc.Models
{
	public class RoundRegistrationDto
	{
		public int Player1_Id { get; set; }

		public int Player2_Id { get; set; }

		public string DateTimeRegistration { get; set; }

		public bool IsJudge { get; set; }

		public string Comment { get; set; }

		public string Language { get; set; }
	}
}

Source/DebateApp.Mvc/Models/View/RegistrationRoundView.cs
using DebateApp.Enum;
using DebateApp.Models;
using System;
using System.Collections.Generic;

namespace DebateApp.Mvc.Models.View
{
	public class RoundRegistrationView
	{
		public IEnumerable<RoundRegistration> Judges;

		public IEnumerable<RoundRegistration> Players;
	}
}

Source/DebateApp.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using DebateApp.Mvc.Models;
using DebateApp.Service;
using DebateApp.Models;
using DebateApp.Enum;

namespace DebateApp.Mvc.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}
}

Source/DebateApp.Mvc/Controllers/RoundRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DebateApp.Mvc.Models.View;
using DebateApp.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DebateApp.Mvc.Controllers
{
	public class RoundRegistrationController : Controller
	{
		private readonly IRoundRegistrationService service;

		public RoundRegistrationController(IRoundRegistrationService service)
		{
			this.service = service;
		}

		public ActionResult GetRegistration()
		{
			var registrations = service.GetResentRegistration(DateTime.Now.Date);

			var registrationsView = new RoundRegistrationView()
			{
				Judges = registrations.Where(r => r.IsJudge),
				Players = registrations.Where(r => !r.IsJudge)
			};

			return View("AllRegistration", registrationsView);
		}
	}
}

Source/DebateApp.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

Дома

Source/DebateApp.Mvc/Views/RoundRegistration/AllRegistration.cshtml
@model DebateApp.Mvc.Models.View.RoundRegistrationView
@Html.Partial("RegistrationModalView")

<div class="row">
	<div class="col-md-4 button-group">
		<button type="button" class="btn btn-dark" data-toggle="modal" data-target="#registrationWindow">Зарегистрироваться на раунд</button>
		<button type="button" class="btn btn-dark" data-toggle="modal" data-target="#registrationWindow">Добавить тиммейта</button>
	</div>
	<div class="col-md-8">
		<h3 style="text-align:center">Список зарегистрированных судей</h3>
		<table class="table">
			<tbody>
			<thead>
				<tr>
					<th scope="col">Судья</th>
					<th scope="col">Дата игры</th>
					<th scope="col">Время игры</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var reg in Model.Judges)
				{
					<tr>
						<td>@reg.Player1.FirstName @reg.Player1.LastName</td>
						<td>@reg.DateTimeRegistration.ToString("D")</td>
						<td>@reg.DateTimeRegistration.ToString("t")</td>
					</tr>
				}
			</tbody>
		</table>
		<h3 style="text-align:center">Список зарегистрированных команд</h3>
		<table class="table">
			<tbody>
			<thead>
				<tr>
					<th scope="col">Первый игрок</th>
					<th scope="col">Второй игрок</th>
					<th scope="col">Дата игры</th>
					<th scope="col">Время игры</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var reg in Model.Players)
				{
					<tr>
						<td>@reg.Player1.FirstName @reg.Player1.LastName</td>
						<td>@reg.Player2.FirstName @reg.Player2.LastName</td>
						<td>@reg.DateTimeRegistration.ToString("D")</td>
						<td>@reg.DateTimeRegistration.ToString("t")</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>


<style>
	.button-group {
		margin-top: 2%;
	}

	.btn-dark {
		color: white;
		background-color: #706e6e;
		margin-bottom: 2%;
		width: 100%;
	}
</style>

Source/DebateApp.Mvc/Views/RoundRegistration/RegistrationModalView.cshtml
<div class="modal fade" id="registrationWindow" tabindex="-1" role="dialog" aria-labelledby="ModalTitle" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="ModalTitle">Регистрация на раунд</h4>
			</div>
			<div class="modal-body">
				<form>
					<div class="form-group">
						<label for="player1" class="col-form-label">Первый игрок:</label>
						<input readonly type="text" class="form-control" id="player1" value="Косыгин Родион">
					</div>
					<div class="form-group">
						<label for="player2" class="col-form-label">Второй игрок:</label>
						<input type="text" class="form-control" id="player2">
					</div>
					<div class="form-group">
						<label for="dateRegistration" class="col-form-label">Дата регистрации:</label>
						<div class="input-group" id="dateRegistration">
							<input type="text" class="form-control" />
							<span class="input-group-addon">
								<span class="glyphicon glyphicon-calendar"></span>
							</span>
						</div>
					</div>
					<div class="form-group">
						<label for="timeRegistration" class="col-form-label">Время регистрации:</label>
						<div class="input-group" id="timeRegistration">
							<input type="text" class="form-control" />
							<span class="input-group-addon">
								<span class="glyphicon glyphicon-time"></span>
							</span>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-dark">Сохранить</button>
			</div>
		</div>
	</div>
</div>

Source/DebateApp.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] Клуб дебатов ДВФУ</title>

	<environment include="Development">
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-datetimepicker.min.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Главная страница</a>
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					@*<li><a asp-area="" asp-controller="Person" asp-action="Index">Зарегистрировать человека</a></li>*@
					<li><a asp-area="" asp-controller="RoundRegistration" asp-action="GetRegistration">Регистрация на раунд</a></li>
				</ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Клуб дебатов ДВФУ</p>
        </footer>
    </div>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/jquery/dist/jquery-3.2.1.min.js"></script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/lib/bootstrap/dist/js/moment-with-locales.min.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap-datetimepicker.min.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>